{{ $global := . }}
apiVersion: v1
kind: Secret
metadata:
  name: registry
  namespace: {{ $global.Values.namespace }}
  labels:
    {{- include "common.labels" $global | indent 4 }}
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}