{{ $global := . }}
{{- range $component := .Values.components }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $component.name }}-secret
  namespace: {{ $global.Values.namespace }}
  labels:
    {{- include "common.labels" $global | indent 4 }}
    app.kubernetes.io/component: {{ $component.name }}
type: Opaque
data:
  {{- range $env := $component.envs }}
  {{- range $key, $value := $env }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
