{{ $global := . }}
{{- range $component := .Values.components }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $component.name }}-route
  namespace: {{ $global.Values.namespace }}
  labels:
    {{- include "common.labels" $global | indent 4 }}
    app.kubernetes.io/component: {{ $component.name }}
spec:
  tls:
    termination: edge
  port:
    targetPort: {{ $component.portName }}
  to:
    kind: Service
    name: {{ $component.name }}-service
{{- end }}
